[alias]
tauri-test = "test --manifest-path src-tauri/Cargo.toml -- --test-threads=1 --nocapture"
tauri-lint = "clippy --manifest-path src-tauri/Cargo.toml -- -D warnings"
tauri-fmt = "fmt --manifest-path src-tauri/Cargo.toml"
